export const DEFAULT_WORKFLOW_NODE_WIDTH = 420

const WORKFLOW_NODE_HORIZONTAL_GUTTER = 140

export const DEFAULT_WORKFLOW_NODE_COLUMN_GAP =
  DEFAULT_WORKFLOW_NODE_WIDTH + WORKFLOW_NODE_HORIZONTAL_GUTTER

export const DEFAULT_WORKFLOW_NODE_ROW_GAP = 340

export const WORKFLOW_NODE_COLLISION_X = DEFAULT_WORKFLOW_NODE_WIDTH + 32
export const WORKFLOW_NODE_COLLISION_Y = 280
